-- AlterTable
ALTER TABLE "Appointment" ADD COLUMN     "employer" TEXT,
ADD COLUMN     "mcEnd" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "mcReason" TEXT,
ADD COLUMN     "mcStart" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
