-- AlterTable
ALTER TABLE "Appointment" ADD COLUMN     "arrivalTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "consultEndTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "consultStartTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "doctor" TEXT NOT NULL DEFAULT 'null',
ADD COLUMN     "documents" TEXT NOT NULL DEFAULT 'null',
ADD COLUMN     "status" TEXT NOT NULL DEFAULT 'waiting';
